package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cluster generated by hbm2java
 */
@Entity
@Table(name = "CLUSTER",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class Cluster implements java.io.Serializable {

    private int idCluster;
    private So so;
    private String descricao;
    private String ipCluster;
    private Set<Vm> vms = new HashSet<Vm>(0);

    public Cluster() {
    }

    public Cluster(So so, String descricao, String ipCluster) {
        this.so = so;
        this.descricao = descricao;
        this.ipCluster = ipCluster;
    }

    public Cluster(int idCluster, So so, String descricao) {
        this.idCluster = idCluster;
        this.so = so;
        this.descricao = descricao;
    }

    public Cluster(int idCluster, So so, String descricao, String ipCluster, Set<Vm> vms) {
        this.idCluster = idCluster;
        this.so = so;
        this.descricao = descricao;
        this.ipCluster = ipCluster;
        this.vms = vms;
    }

    public Cluster(String descricao, String ipCluster) {
        this.descricao = descricao;
        this.ipCluster = ipCluster;
    }

    @Id

    @Column(name = "ID_CLUSTER", unique = true, nullable = false)
    public int getIdCluster() {
        return this.idCluster;
    }

    public void setIdCluster(int idCluster) {
        this.idCluster = idCluster;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SO", nullable = false)
    public So getSo() {
        return this.so;
    }

    public void setSo(So so) {
        this.so = so;
    }

    @Column(name = "DESCRICAO", nullable = false, length = 100)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "IP_CLUSTER", length = 50)
    public String getIpCluster() {
        return this.ipCluster;
    }

    public void setIpCluster(String ipCluster) {
        this.ipCluster = ipCluster;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cluster")
    public Set<Vm> getVms() {
        return this.vms;
    }

    public void setVms(Set<Vm> vms) {
        this.vms = vms;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.so);
        hash = 47 * hash + Objects.hashCode(this.descricao);
        hash = 47 * hash + Objects.hashCode(this.ipCluster);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cluster other = (Cluster) obj;
        if (!Objects.equals(this.descricao.toLowerCase(), other.descricao.toLowerCase())) {
            return false;
        }
        if (!Objects.equals(this.ipCluster.toLowerCase(), other.ipCluster.toLowerCase())) {
            return false;
        }
        return Objects.equals(this.so, other.so);
    }

    @Override
    public String toString() {
        return descricao;
    }

}
