package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LinhaSistema generated by hbm2java
 */
@Entity
@Table(name = "LINHA_SISTEMA",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class LinhaSistema implements java.io.Serializable {

    private int idLinhaSistema;
    private String nome;
    private Set<Programa> programas = new HashSet<Programa>(0);

    public LinhaSistema() {
    }

    public LinhaSistema(String nome) {
        this.nome = nome;
    }

    public LinhaSistema(int idLinhaSistema) {
        this.idLinhaSistema = idLinhaSistema;
    }

    public LinhaSistema(int idLinhaSistema, String nome, Set<Programa> programas) {
        this.idLinhaSistema = idLinhaSistema;
        this.nome = nome;
        this.programas = programas;
    }

    @Id

    @Column(name = "ID_LINHA_SISTEMA", unique = true, nullable = false)
    public int getIdLinhaSistema() {
        return this.idLinhaSistema;
    }

    public void setIdLinhaSistema(int idLinhaSistema) {
        this.idLinhaSistema = idLinhaSistema;
    }

    @Column(name = "NOME", length = 100)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "linhaSistema")
    public Set<Programa> getProgramas() {
        return this.programas;
    }

    public void setProgramas(Set<Programa> programas) {
        this.programas = programas;
    }

    @Override
    public String toString() {
        return nome;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LinhaSistema other = (LinhaSistema) obj;
        return Objects.equals(this.nome.toLowerCase(), other.nome.toLowerCase());
    }

}
