package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "PERFIL",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class Perfil implements java.io.Serializable {

    private int idPerfil;
    private String codperfil;
    private String textoMenu;
    private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Perfil() {
    }

    public Perfil(String codperfil, String textoMenu) {
        this.codperfil = codperfil;
        this.textoMenu = textoMenu;
    }

    public Perfil(int idPerfil, String codperfil, String textoMenu) {
        this.idPerfil = idPerfil;
        this.codperfil = codperfil;
        this.textoMenu = textoMenu;
    }

    public Perfil(int idPerfil, String codperfil, String textoMenu, Set<Usuario> usuarios) {
        this.idPerfil = idPerfil;
        this.codperfil = codperfil;
        this.textoMenu = textoMenu;
        this.usuarios = usuarios;
    }

    public Perfil(String codperfil) {
        this.codperfil = codperfil;
    }

    @Id

    @Column(name = "ID_PERFIL", unique = true, nullable = false)
    public int getIdPerfil() {
        return this.idPerfil;
    }

    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }

    @Column(name = "CODPERFIL", nullable = false, length = 50)
    public String getCodperfil() {
        return this.codperfil;
    }

    public void setCodperfil(String codperfil) {
        this.codperfil = codperfil;
    }

    @Column(name = "TEXTO_MENU", nullable = false, length = 4000)
    public String getTextoMenu() {
        return this.textoMenu;
    }

    public void setTextoMenu(String textoMenu) {
        this.textoMenu = textoMenu;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return codperfil;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 13 * hash + Objects.hashCode(this.codperfil);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Perfil other = (Perfil) obj;
        return Objects.equals(this.codperfil.toLowerCase(), other.codperfil.toLowerCase());
    }

}
