package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgramasVmHst generated by hbm2java
 */
@Entity
@Table(name = "PROGRAMAS_VM_HST",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class ProgramasVmHst implements java.io.Serializable {

    private int idHts;
    private ProgramasVm programasVm;
    private String versao;
    private Date dtatualizacao;
    private String observacao;

    public ProgramasVmHst() {
    }

    public ProgramasVmHst(int idHts, ProgramasVm programasVm, String versao, Date dtatualizacao) {
        this.idHts = idHts;
        this.programasVm = programasVm;
        this.versao = versao;
        this.dtatualizacao = dtatualizacao;
    }

    public ProgramasVmHst(int idHts, ProgramasVm programasVm, String versao, Date dtatualizacao, String observacao) {
        this.idHts = idHts;
        this.programasVm = programasVm;
        this.versao = versao;
        this.dtatualizacao = dtatualizacao;
        this.observacao = observacao;
    }

    public ProgramasVmHst(ProgramasVm programasVm, String versao, Date dtatualizacao, String observacao) {
        this.programasVm = programasVm;
        this.versao = versao;
        this.dtatualizacao = dtatualizacao;
        this.observacao = observacao;
    }

    public ProgramasVmHst(String versao, Date dtatualizacao) {
        this.versao = versao;
        this.dtatualizacao = dtatualizacao;
    }

    @Id

    @Column(name = "ID_HTS", unique = true, nullable = false)
    public int getIdHts() {
        return this.idHts;
    }

    public void setIdHts(int idHts) {
        this.idHts = idHts;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROGRAMAS_VM", nullable = false)
    public ProgramasVm getProgramasVm() {
        return this.programasVm;
    }

    public void setProgramasVm(ProgramasVm programasVm) {
        this.programasVm = programasVm;
    }

    @Column(name = "VERSAO", nullable = false, length = 100)
    public String getVersao() {
        return this.versao;
    }

    public void setVersao(String versao) {
        this.versao = versao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DTATUALIZACAO", nullable = false, length = 23)
    public Date getDtatualizacao() {
        return this.dtatualizacao;
    }

    public void setDtatualizacao(Date dtatualizacao) {
        this.dtatualizacao = dtatualizacao;
    }

    @Column(name = "OBSERVACAO", length = 4000)
    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + Objects.hashCode(this.versao);
        hash = 67 * hash + Objects.hashCode(this.dtatualizacao);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ProgramasVmHst other = (ProgramasVmHst) obj;
        if (!Objects.equals(this.versao, other.versao)) {
            return false;
        }
        if (!Objects.equals(this.dtatualizacao, other.dtatualizacao)) {
            return false;
        }
        return true;
    }

}
