package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programa generated by hbm2java
 */
@Entity
@Table(name = "PROGRAMA",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class Programa implements java.io.Serializable {

    private int idPrograma;
    private LinhaSistema linhaSistema;
    private String nome;
    private Set<ProgramasVm> programasVms = new HashSet<ProgramasVm>(0);

    public Programa() {
    }

    public Programa(LinhaSistema linhaSistema, String nome) {
        this.linhaSistema = linhaSistema;
        this.nome = nome;
    }

    public Programa(int idPrograma, LinhaSistema linhaSistema, String nome) {
        this.idPrograma = idPrograma;
        this.linhaSistema = linhaSistema;
        this.nome = nome;
    }

    public Programa(int idPrograma, LinhaSistema linhaSistema, String nome, Set<ProgramasVm> programasVms) {
        this.idPrograma = idPrograma;
        this.linhaSistema = linhaSistema;
        this.nome = nome;
        this.programasVms = programasVms;
    }

    public Programa(String nome) {
        this.nome = nome;
    }

    @Id

    @Column(name = "ID_PROGRAMA", unique = true, nullable = false)
    public int getIdPrograma() {
        return this.idPrograma;
    }

    public void setIdPrograma(int idPrograma) {
        this.idPrograma = idPrograma;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_LINHA_SISTEMA", nullable = false)
    public LinhaSistema getLinhaSistema() {
        return this.linhaSistema;
    }

    public void setLinhaSistema(LinhaSistema linhaSistema) {
        this.linhaSistema = linhaSistema;
    }

    @Column(name = "NOME", nullable = false, length = 100)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "programa")
    public Set<ProgramasVm> getProgramasVms() {
        return this.programasVms;
    }

    public void setProgramasVms(Set<ProgramasVm> programasVms) {
        this.programasVms = programasVms;
    }

    @Override
    public String toString() {
        return nome;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.nome);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Programa other = (Programa) obj;
        return Objects.equals(this.nome.toLowerCase(), other.nome.toLowerCase());
    }

}
