package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicosVm generated by hbm2java
 */
@Entity
@Table(name = "SERVICOS_VM",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class ServicosVm implements java.io.Serializable {

    private int idServicosVm;
    private ProgramasVm programasVm;
    private Servico servico;

    public ServicosVm() {
    }

    public ServicosVm(int idServicosVm, ProgramasVm programasVm, Servico servico) {
        this.idServicosVm = idServicosVm;
        this.programasVm = programasVm;
        this.servico = servico;
    }

    public ServicosVm(ProgramasVm programasVm, Servico servico) {
        this.programasVm = programasVm;
        this.servico = servico;
    }

    public ServicosVm(ProgramasVm programasVm) {
        this.programasVm = programasVm;
    }

    @Id

    @Column(name = "ID_SERVICOS_VM", unique = true, nullable = false)
    public int getIdServicosVm() {
        return this.idServicosVm;
    }

    public void setIdServicosVm(int idServicosVm) {
        this.idServicosVm = idServicosVm;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROGRAMAS_VM", nullable = false)
    public ProgramasVm getProgramasVm() {
        return this.programasVm;
    }

    public void setProgramasVm(ProgramasVm programasVm) {
        this.programasVm = programasVm;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SERVICO", nullable = false)
    public Servico getServico() {
        return this.servico;
    }

    public void setServico(Servico servico) {
        this.servico = servico;
    }

    @Override
    public String toString() {
        return programasVm.toString();
    }

}
