package br.com.tbsa.entity;
// Generated 09/05/2018 20:17:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * So generated by hbm2java
 */
@Entity
@Table(name = "SO",
        schema = "dbo",
        catalog = "BIGEYE"
)
public class So implements java.io.Serializable {

    private int idSo;
    private String descricao;
    private Set<Cluster> clusters = new HashSet<Cluster>(0);
    private Set<Vm> vms = new HashSet<Vm>(0);

    public So() {
    }

    public So(String descricao) {
        this.descricao = descricao;
    }

    public So(int idSo) {
        this.idSo = idSo;
    }

    public So(int idSo, String descricao, Set<Cluster> clusters, Set<Vm> vms) {
        this.idSo = idSo;
        this.descricao = descricao;
        this.clusters = clusters;
        this.vms = vms;
    }

    @Id

    @Column(name = "ID_SO", unique = true, nullable = false)
    public int getIdSo() {
        return this.idSo;
    }

    public void setIdSo(int idSo) {
        this.idSo = idSo;
    }

    @Column(name = "DESCRICAO", length = 100)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "so")
    public Set<Cluster> getClusters() {
        return this.clusters;
    }

    public void setClusters(Set<Cluster> clusters) {
        this.clusters = clusters;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "so")
    public Set<Vm> getVms() {
        return this.vms;
    }

    public void setVms(Set<Vm> vms) {
        this.vms = vms;
    }

    @Override
    public String toString() {
        return descricao;
    }

}
